/* BudgieMenu.c generated by valac 0.32.1, the Vala compiler
 * generated from BudgieMenu.vala, do not modify */

/*
 * This file is part of budgie-desktop
 * 
 * Copyright (C) 2015-2016 Ikey Doherty <ikey@solus-project.com>
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 */

#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <gdk/gdk.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>


#define TYPE_BUDGIE_MENU_APPLET (budgie_menu_applet_get_type ())
#define BUDGIE_MENU_APPLET(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_BUDGIE_MENU_APPLET, BudgieMenuApplet))
#define BUDGIE_MENU_APPLET_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_BUDGIE_MENU_APPLET, BudgieMenuAppletClass))
#define IS_BUDGIE_MENU_APPLET(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_BUDGIE_MENU_APPLET))
#define IS_BUDGIE_MENU_APPLET_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_BUDGIE_MENU_APPLET))
#define BUDGIE_MENU_APPLET_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_BUDGIE_MENU_APPLET, BudgieMenuAppletClass))

typedef struct _BudgieMenuApplet BudgieMenuApplet;
typedef struct _BudgieMenuAppletClass BudgieMenuAppletClass;
typedef struct _BudgieMenuAppletPrivate BudgieMenuAppletPrivate;

#define TYPE_BUDGIE_MENU_WINDOW (budgie_menu_window_get_type ())
#define BUDGIE_MENU_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_BUDGIE_MENU_WINDOW, BudgieMenuWindow))
#define BUDGIE_MENU_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_BUDGIE_MENU_WINDOW, BudgieMenuWindowClass))
#define IS_BUDGIE_MENU_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_BUDGIE_MENU_WINDOW))
#define IS_BUDGIE_MENU_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_BUDGIE_MENU_WINDOW))
#define BUDGIE_MENU_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_BUDGIE_MENU_WINDOW, BudgieMenuWindowClass))

typedef struct _BudgieMenuWindow BudgieMenuWindow;
typedef struct _BudgieMenuWindowClass BudgieMenuWindowClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_option_context_free0(var) ((var == NULL) ? NULL : (var = (g_option_context_free (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

struct _BudgieMenuApplet {
	GtkWindow parent_instance;
	BudgieMenuAppletPrivate * priv;
	GtkToggleButton* widget;
	BudgieMenuWindow* popover;
};

struct _BudgieMenuAppletClass {
	GtkWindowClass parent_class;
};

struct _BudgieMenuAppletPrivate {
	GtkImage* img;
	GtkLabel* label;
};


static gpointer budgie_menu_applet_parent_class = NULL;

GType budgie_menu_applet_get_type (void) G_GNUC_CONST;
GType budgie_menu_window_get_type (void) G_GNUC_CONST;
#define BUDGIE_MENU_APPLET_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_BUDGIE_MENU_APPLET, BudgieMenuAppletPrivate))
enum  {
	BUDGIE_MENU_APPLET_DUMMY_PROPERTY
};
BudgieMenuApplet* budgie_menu_applet_new (void);
BudgieMenuApplet* budgie_menu_applet_construct (GType object_type);
BudgieMenuWindow* budgie_menu_window_new (GtkWidget* leparent);
BudgieMenuWindow* budgie_menu_window_construct (GType object_type, GtkWidget* leparent);
static gboolean __lambda13_ (BudgieMenuApplet* self, GdkEventButton* e);
static gboolean ___lambda13__gtk_widget_button_press_event (GtkWidget* _sender, GdkEventButton* event, gpointer self);
static gboolean __lambda14_ (BudgieMenuApplet* self, GdkEventKey* e);
static gboolean ___lambda14__gtk_widget_key_release_event (GtkWidget* _sender, GdkEventKey* event, gpointer self);
static void budgie_menu_applet_finalize (GObject* obj);
void _vala_main (gchar** args, int args_length1);
static void _gtk_main_quit_gtk_widget_destroy (GtkWidget* _sender, gpointer self);


static gpointer _g_object_ref0 (gpointer self) {
#line 39 "BudgieMenu.vala"
	return self ? g_object_ref (self) : NULL;
#line 90 "BudgieMenu.c"
}


static gboolean __lambda13_ (BudgieMenuApplet* self, GdkEventButton* e) {
	gboolean result = FALSE;
	GdkEventButton* _tmp0_ = NULL;
	guint _tmp1_ = 0U;
	BudgieMenuWindow* _tmp2_ = NULL;
	gboolean _tmp3_ = FALSE;
#line 45 "BudgieMenu.vala"
	g_return_val_if_fail (e != NULL, FALSE);
#line 46 "BudgieMenu.vala"
	_tmp0_ = e;
#line 46 "BudgieMenu.vala"
	_tmp1_ = _tmp0_->button;
#line 46 "BudgieMenu.vala"
	if (_tmp1_ != ((guint) 1)) {
#line 47 "BudgieMenu.vala"
		result = GDK_EVENT_PROPAGATE;
#line 47 "BudgieMenu.vala"
		return result;
#line 112 "BudgieMenu.c"
	}
#line 49 "BudgieMenu.vala"
	_tmp2_ = self->popover;
#line 49 "BudgieMenu.vala"
	_tmp3_ = gtk_widget_get_visible (G_TYPE_CHECK_INSTANCE_CAST (_tmp2_, gtk_widget_get_type (), GtkWidget));
#line 49 "BudgieMenu.vala"
	if (_tmp3_) {
#line 120 "BudgieMenu.c"
		BudgieMenuWindow* _tmp4_ = NULL;
#line 50 "BudgieMenu.vala"
		_tmp4_ = self->popover;
#line 50 "BudgieMenu.vala"
		gtk_widget_hide (G_TYPE_CHECK_INSTANCE_CAST (_tmp4_, gtk_widget_get_type (), GtkWidget));
#line 126 "BudgieMenu.c"
	} else {
		BudgieMenuWindow* _tmp5_ = NULL;
		GtkWidget* _tmp6_ = NULL;
		BudgieMenuWindow* _tmp7_ = NULL;
#line 52 "BudgieMenu.vala"
		_tmp5_ = self->popover;
#line 52 "BudgieMenu.vala"
		_tmp6_ = gtk_bin_get_child (G_TYPE_CHECK_INSTANCE_CAST (_tmp5_, gtk_bin_get_type (), GtkBin));
#line 52 "BudgieMenu.vala"
		gtk_widget_show_all (_tmp6_);
#line 53 "BudgieMenu.vala"
		_tmp7_ = self->popover;
#line 53 "BudgieMenu.vala"
		gtk_widget_show (G_TYPE_CHECK_INSTANCE_CAST (_tmp7_, gtk_widget_get_type (), GtkWidget));
#line 141 "BudgieMenu.c"
	}
#line 55 "BudgieMenu.vala"
	result = GDK_EVENT_STOP;
#line 55 "BudgieMenu.vala"
	return result;
#line 147 "BudgieMenu.c"
}


static gboolean ___lambda13__gtk_widget_button_press_event (GtkWidget* _sender, GdkEventButton* event, gpointer self) {
	gboolean result;
	result = __lambda13_ ((BudgieMenuApplet*) self, event);
#line 45 "BudgieMenu.vala"
	return result;
#line 156 "BudgieMenu.c"
}


static gboolean __lambda14_ (BudgieMenuApplet* self, GdkEventKey* e) {
	gboolean result = FALSE;
	GdkEventKey* _tmp0_ = NULL;
	guint _tmp1_ = 0U;
#line 68 "BudgieMenu.vala"
	g_return_val_if_fail (e != NULL, FALSE);
#line 69 "BudgieMenu.vala"
	_tmp0_ = e;
#line 69 "BudgieMenu.vala"
	_tmp1_ = _tmp0_->keyval;
#line 69 "BudgieMenu.vala"
	if (_tmp1_ == ((guint) GDK_KEY_Escape)) {
#line 172 "BudgieMenu.c"
		BudgieMenuWindow* _tmp2_ = NULL;
#line 70 "BudgieMenu.vala"
		_tmp2_ = self->popover;
#line 70 "BudgieMenu.vala"
		gtk_widget_hide (G_TYPE_CHECK_INSTANCE_CAST (_tmp2_, gtk_widget_get_type (), GtkWidget));
#line 178 "BudgieMenu.c"
	}
#line 72 "BudgieMenu.vala"
	result = GDK_EVENT_PROPAGATE;
#line 72 "BudgieMenu.vala"
	return result;
#line 184 "BudgieMenu.c"
}


static gboolean ___lambda14__gtk_widget_key_release_event (GtkWidget* _sender, GdkEventKey* event, gpointer self) {
	gboolean result;
	result = __lambda14_ ((BudgieMenuApplet*) self, event);
#line 68 "BudgieMenu.vala"
	return result;
#line 193 "BudgieMenu.c"
}


BudgieMenuApplet* budgie_menu_applet_construct (GType object_type) {
	BudgieMenuApplet * self = NULL;
	GtkToggleButton* _tmp0_ = NULL;
	GtkToggleButton* _tmp1_ = NULL;
	GtkImage* _tmp2_ = NULL;
	GtkImage* _tmp3_ = NULL;
	GtkBox* layout = NULL;
	GtkBox* _tmp4_ = NULL;
	GtkImage* _tmp5_ = NULL;
	GtkLabel* _tmp6_ = NULL;
	GtkLabel* _tmp7_ = NULL;
	GtkLabel* _tmp8_ = NULL;
	GtkToggleButton* _tmp9_ = NULL;
	GtkStyleContext* st = NULL;
	GtkToggleButton* _tmp10_ = NULL;
	GtkStyleContext* _tmp11_ = NULL;
	GtkStyleContext* _tmp12_ = NULL;
	GtkToggleButton* _tmp13_ = NULL;
	BudgieMenuWindow* _tmp14_ = NULL;
	BudgieMenuWindow* _tmp15_ = NULL;
	GtkToggleButton* _tmp16_ = NULL;
	GtkToggleButton* _tmp17_ = NULL;
	BudgieMenuWindow* _tmp18_ = NULL;
	GtkWidget* _tmp19_ = NULL;
	GtkToggleButton* _tmp20_ = NULL;
	GtkToggleButton* _tmp21_ = NULL;
	GtkToggleButton* _tmp22_ = NULL;
	BudgieMenuWindow* _tmp23_ = NULL;
#line 23 "BudgieMenu.vala"
	self = (BudgieMenuApplet*) g_object_new (object_type, "type", GTK_WINDOW_TOPLEVEL, NULL);
#line 25 "BudgieMenu.vala"
	_tmp0_ = (GtkToggleButton*) gtk_toggle_button_new ();
#line 25 "BudgieMenu.vala"
	g_object_ref_sink (_tmp0_);
#line 25 "BudgieMenu.vala"
	_g_object_unref0 (self->widget);
#line 25 "BudgieMenu.vala"
	self->widget = _tmp0_;
#line 26 "BudgieMenu.vala"
	_tmp1_ = self->widget;
#line 26 "BudgieMenu.vala"
	gtk_button_set_relief (G_TYPE_CHECK_INSTANCE_CAST (_tmp1_, gtk_button_get_type (), GtkButton), GTK_RELIEF_NONE);
#line 27 "BudgieMenu.vala"
	_tmp2_ = (GtkImage*) gtk_image_new_from_icon_name ("view-grid-symbolic", GTK_ICON_SIZE_INVALID);
#line 27 "BudgieMenu.vala"
	g_object_ref_sink (_tmp2_);
#line 27 "BudgieMenu.vala"
	_g_object_unref0 (self->priv->img);
#line 27 "BudgieMenu.vala"
	self->priv->img = _tmp2_;
#line 28 "BudgieMenu.vala"
	_tmp3_ = self->priv->img;
#line 28 "BudgieMenu.vala"
	gtk_image_set_pixel_size (_tmp3_, 32);
#line 30 "BudgieMenu.vala"
	_tmp4_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_HORIZONTAL, 0);
#line 30 "BudgieMenu.vala"
	g_object_ref_sink (_tmp4_);
#line 30 "BudgieMenu.vala"
	layout = _tmp4_;
#line 31 "BudgieMenu.vala"
	_tmp5_ = self->priv->img;
#line 31 "BudgieMenu.vala"
	gtk_box_pack_start (layout, G_TYPE_CHECK_INSTANCE_CAST (_tmp5_, gtk_widget_get_type (), GtkWidget), FALSE, FALSE, (guint) 3);
#line 32 "BudgieMenu.vala"
	_tmp6_ = (GtkLabel*) gtk_label_new ("");
#line 32 "BudgieMenu.vala"
	g_object_ref_sink (_tmp6_);
#line 32 "BudgieMenu.vala"
	_g_object_unref0 (self->priv->label);
#line 32 "BudgieMenu.vala"
	self->priv->label = _tmp6_;
#line 33 "BudgieMenu.vala"
	_tmp7_ = self->priv->label;
#line 33 "BudgieMenu.vala"
	gtk_widget_set_halign (G_TYPE_CHECK_INSTANCE_CAST (_tmp7_, gtk_widget_get_type (), GtkWidget), GTK_ALIGN_START);
#line 34 "BudgieMenu.vala"
	_tmp8_ = self->priv->label;
#line 34 "BudgieMenu.vala"
	gtk_box_pack_start (layout, G_TYPE_CHECK_INSTANCE_CAST (_tmp8_, gtk_widget_get_type (), GtkWidget), TRUE, TRUE, (guint) 3);
#line 36 "BudgieMenu.vala"
	_tmp9_ = self->widget;
#line 36 "BudgieMenu.vala"
	gtk_container_add (G_TYPE_CHECK_INSTANCE_CAST (_tmp9_, gtk_container_get_type (), GtkContainer), G_TYPE_CHECK_INSTANCE_CAST (layout, gtk_widget_get_type (), GtkWidget));
#line 39 "BudgieMenu.vala"
	_tmp10_ = self->widget;
#line 39 "BudgieMenu.vala"
	_tmp11_ = gtk_widget_get_style_context (G_TYPE_CHECK_INSTANCE_CAST (_tmp10_, gtk_widget_get_type (), GtkWidget));
#line 39 "BudgieMenu.vala"
	_tmp12_ = _g_object_ref0 (_tmp11_);
#line 39 "BudgieMenu.vala"
	st = _tmp12_;
#line 40 "BudgieMenu.vala"
	gtk_style_context_add_class (st, "budgie-menu-launcher");
#line 41 "BudgieMenu.vala"
	gtk_style_context_add_class (st, "panel-button");
#line 42 "BudgieMenu.vala"
	_tmp13_ = self->widget;
#line 42 "BudgieMenu.vala"
	_tmp14_ = budgie_menu_window_new (G_TYPE_CHECK_INSTANCE_CAST (_tmp13_, gtk_widget_get_type (), GtkWidget));
#line 42 "BudgieMenu.vala"
	g_object_ref_sink (_tmp14_);
#line 42 "BudgieMenu.vala"
	_g_object_unref0 (self->popover);
#line 42 "BudgieMenu.vala"
	self->popover = _tmp14_;
#line 43 "BudgieMenu.vala"
	_tmp15_ = self->popover;
#line 43 "BudgieMenu.vala"
	_tmp16_ = self->widget;
#line 43 "BudgieMenu.vala"
	g_object_bind_property_with_closures (G_TYPE_CHECK_INSTANCE_CAST (_tmp15_, G_TYPE_OBJECT, GObject), "visible", G_TYPE_CHECK_INSTANCE_CAST (_tmp16_, G_TYPE_OBJECT, GObject), "active", G_BINDING_DEFAULT, (GClosure*) ((NULL == NULL) ? NULL : g_cclosure_new ((GCallback) NULL, NULL, NULL)), (GClosure*) ((NULL == NULL) ? NULL : g_cclosure_new ((GCallback) NULL, NULL, NULL)));
#line 45 "BudgieMenu.vala"
	_tmp17_ = self->widget;
#line 45 "BudgieMenu.vala"
	g_signal_connect_object (G_TYPE_CHECK_INSTANCE_CAST (_tmp17_, gtk_widget_get_type (), GtkWidget), "button-press-event", (GCallback) ___lambda13__gtk_widget_button_press_event, self, 0);
#line 58 "BudgieMenu.vala"
	_tmp18_ = self->popover;
#line 58 "BudgieMenu.vala"
	_tmp19_ = gtk_bin_get_child (G_TYPE_CHECK_INSTANCE_CAST (_tmp18_, gtk_bin_get_type (), GtkBin));
#line 58 "BudgieMenu.vala"
	gtk_widget_show_all (_tmp19_);
#line 60 "BudgieMenu.vala"
	_tmp20_ = self->widget;
#line 60 "BudgieMenu.vala"
	gtk_container_add (G_TYPE_CHECK_INSTANCE_CAST (self, gtk_container_get_type (), GtkContainer), G_TYPE_CHECK_INSTANCE_CAST (_tmp20_, gtk_widget_get_type (), GtkWidget));
#line 61 "BudgieMenu.vala"
	_tmp21_ = self->widget;
#line 61 "BudgieMenu.vala"
	gtk_widget_set_halign (G_TYPE_CHECK_INSTANCE_CAST (_tmp21_, gtk_widget_get_type (), GtkWidget), GTK_ALIGN_START);
#line 62 "BudgieMenu.vala"
	_tmp22_ = self->widget;
#line 62 "BudgieMenu.vala"
	gtk_widget_set_valign (G_TYPE_CHECK_INSTANCE_CAST (_tmp22_, gtk_widget_get_type (), GtkWidget), GTK_ALIGN_START);
#line 63 "BudgieMenu.vala"
	gtk_widget_show_all (G_TYPE_CHECK_INSTANCE_CAST (self, gtk_widget_get_type (), GtkWidget));
#line 64 "BudgieMenu.vala"
	gtk_widget_set_valign (G_TYPE_CHECK_INSTANCE_CAST (layout, gtk_widget_get_type (), GtkWidget), GTK_ALIGN_CENTER);
#line 65 "BudgieMenu.vala"
	gtk_widget_set_valign (G_TYPE_CHECK_INSTANCE_CAST (self, gtk_widget_get_type (), GtkWidget), GTK_ALIGN_FILL);
#line 66 "BudgieMenu.vala"
	gtk_widget_set_halign (G_TYPE_CHECK_INSTANCE_CAST (self, gtk_widget_get_type (), GtkWidget), GTK_ALIGN_FILL);
#line 68 "BudgieMenu.vala"
	_tmp23_ = self->popover;
#line 68 "BudgieMenu.vala"
	g_signal_connect_object (G_TYPE_CHECK_INSTANCE_CAST (_tmp23_, gtk_widget_get_type (), GtkWidget), "key-release-event", (GCallback) ___lambda14__gtk_widget_key_release_event, self, 0);
#line 21 "BudgieMenu.vala"
	_g_object_unref0 (st);
#line 21 "BudgieMenu.vala"
	_g_object_unref0 (layout);
#line 21 "BudgieMenu.vala"
	return self;
#line 349 "BudgieMenu.c"
}


BudgieMenuApplet* budgie_menu_applet_new (void) {
#line 21 "BudgieMenu.vala"
	return budgie_menu_applet_construct (TYPE_BUDGIE_MENU_APPLET);
#line 356 "BudgieMenu.c"
}


static void budgie_menu_applet_class_init (BudgieMenuAppletClass * klass) {
#line 13 "BudgieMenu.vala"
	budgie_menu_applet_parent_class = g_type_class_peek_parent (klass);
#line 13 "BudgieMenu.vala"
	g_type_class_add_private (klass, sizeof (BudgieMenuAppletPrivate));
#line 13 "BudgieMenu.vala"
	G_OBJECT_CLASS (klass)->finalize = budgie_menu_applet_finalize;
#line 367 "BudgieMenu.c"
}


static void budgie_menu_applet_instance_init (BudgieMenuApplet * self) {
#line 13 "BudgieMenu.vala"
	self->priv = BUDGIE_MENU_APPLET_GET_PRIVATE (self);
#line 374 "BudgieMenu.c"
}


static void budgie_menu_applet_finalize (GObject* obj) {
	BudgieMenuApplet * self;
#line 13 "BudgieMenu.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_BUDGIE_MENU_APPLET, BudgieMenuApplet);
#line 16 "BudgieMenu.vala"
	_g_object_unref0 (self->widget);
#line 17 "BudgieMenu.vala"
	_g_object_unref0 (self->popover);
#line 18 "BudgieMenu.vala"
	_g_object_unref0 (self->priv->img);
#line 19 "BudgieMenu.vala"
	_g_object_unref0 (self->priv->label);
#line 13 "BudgieMenu.vala"
	G_OBJECT_CLASS (budgie_menu_applet_parent_class)->finalize (obj);
#line 392 "BudgieMenu.c"
}


GType budgie_menu_applet_get_type (void) {
	static volatile gsize budgie_menu_applet_type_id__volatile = 0;
	if (g_once_init_enter (&budgie_menu_applet_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (BudgieMenuAppletClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) budgie_menu_applet_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (BudgieMenuApplet), 0, (GInstanceInitFunc) budgie_menu_applet_instance_init, NULL };
		GType budgie_menu_applet_type_id;
		budgie_menu_applet_type_id = g_type_register_static (gtk_window_get_type (), "BudgieMenuApplet", &g_define_type_info, 0);
		g_once_init_leave (&budgie_menu_applet_type_id__volatile, budgie_menu_applet_type_id);
	}
	return budgie_menu_applet_type_id__volatile;
}


static void _gtk_main_quit_gtk_widget_destroy (GtkWidget* _sender, gpointer self) {
#line 97 "BudgieMenu.vala"
	gtk_main_quit ();
#line 411 "BudgieMenu.c"
}


void _vala_main (gchar** args, int args_length1) {
	GOptionContext* ctx = NULL;
	GOptionContext* _tmp0_ = NULL;
	GOptionContext* _tmp1_ = NULL;
	GOptionContext* _tmp2_ = NULL;
	GOptionGroup* _tmp3_ = NULL;
	BudgieMenuApplet* win = NULL;
	BudgieMenuApplet* _tmp8_ = NULL;
	GtkSettings* settings = NULL;
	GtkSettings* _tmp9_ = NULL;
	GtkSettings* _tmp10_ = NULL;
	GtkSettings* _tmp11_ = NULL;
	BudgieMenuApplet* _tmp12_ = NULL;
	BudgieMenuApplet* _tmp13_ = NULL;
	BudgieMenuApplet* _tmp14_ = NULL;
	BudgieMenuApplet* _tmp15_ = NULL;
	GError * _inner_error_ = NULL;
#line 80 "BudgieMenu.vala"
	gtk_init (&args_length1, &args);
#line 83 "BudgieMenu.vala"
	_tmp0_ = g_option_context_new ("- Budgie Menu");
#line 83 "BudgieMenu.vala"
	_g_option_context_free0 (ctx);
#line 83 "BudgieMenu.vala"
	ctx = _tmp0_;
#line 84 "BudgieMenu.vala"
	_tmp1_ = ctx;
#line 84 "BudgieMenu.vala"
	g_option_context_set_help_enabled (_tmp1_, TRUE);
#line 85 "BudgieMenu.vala"
	_tmp2_ = ctx;
#line 85 "BudgieMenu.vala"
	_tmp3_ = gtk_get_option_group (FALSE);
#line 85 "BudgieMenu.vala"
	g_option_context_add_group (_tmp2_, _tmp3_);
#line 450 "BudgieMenu.c"
	{
		GOptionContext* _tmp4_ = NULL;
#line 88 "BudgieMenu.vala"
		_tmp4_ = ctx;
#line 88 "BudgieMenu.vala"
		g_option_context_parse (_tmp4_, &args_length1, &args, &_inner_error_);
#line 88 "BudgieMenu.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 459 "BudgieMenu.c"
			goto __catch0_g_error;
		}
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* e = NULL;
		FILE* _tmp5_ = NULL;
		GError* _tmp6_ = NULL;
		const gchar* _tmp7_ = NULL;
#line 87 "BudgieMenu.vala"
		e = _inner_error_;
#line 87 "BudgieMenu.vala"
		_inner_error_ = NULL;
#line 90 "BudgieMenu.vala"
		_tmp5_ = stderr;
#line 90 "BudgieMenu.vala"
		_tmp6_ = e;
#line 90 "BudgieMenu.vala"
		_tmp7_ = _tmp6_->message;
#line 90 "BudgieMenu.vala"
		fprintf (_tmp5_, "Error: %s\n", _tmp7_);
#line 91 "BudgieMenu.vala"
		_g_error_free0 (e);
#line 91 "BudgieMenu.vala"
		_g_option_context_free0 (ctx);
#line 91 "BudgieMenu.vala"
		return;
#line 488 "BudgieMenu.c"
	}
	__finally0:
#line 87 "BudgieMenu.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 87 "BudgieMenu.vala"
		_g_option_context_free0 (ctx);
#line 87 "BudgieMenu.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 87 "BudgieMenu.vala"
		g_clear_error (&_inner_error_);
#line 87 "BudgieMenu.vala"
		return;
#line 501 "BudgieMenu.c"
	}
#line 94 "BudgieMenu.vala"
	_tmp8_ = budgie_menu_applet_new ();
#line 94 "BudgieMenu.vala"
	g_object_ref_sink (_tmp8_);
#line 94 "BudgieMenu.vala"
	win = _tmp8_;
#line 95 "BudgieMenu.vala"
	_tmp9_ = gtk_settings_get_default ();
#line 95 "BudgieMenu.vala"
	_tmp10_ = _g_object_ref0 (_tmp9_);
#line 95 "BudgieMenu.vala"
	settings = _tmp10_;
#line 96 "BudgieMenu.vala"
	_tmp11_ = settings;
#line 96 "BudgieMenu.vala"
	g_object_set (G_TYPE_CHECK_INSTANCE_CAST (_tmp11_, G_TYPE_OBJECT, GObject), "gtk-application-prefer-dark-theme", TRUE, NULL);
#line 97 "BudgieMenu.vala"
	_tmp12_ = win;
#line 97 "BudgieMenu.vala"
	g_signal_connect (G_TYPE_CHECK_INSTANCE_CAST (_tmp12_, gtk_widget_get_type (), GtkWidget), "destroy", (GCallback) _gtk_main_quit_gtk_widget_destroy, NULL);
#line 98 "BudgieMenu.vala"
	_tmp13_ = win;
#line 98 "BudgieMenu.vala"
	gtk_window_set_position (G_TYPE_CHECK_INSTANCE_CAST (_tmp13_, gtk_window_get_type (), GtkWindow), GTK_WIN_POS_CENTER);
#line 99 "BudgieMenu.vala"
	_tmp14_ = win;
#line 99 "BudgieMenu.vala"
	gtk_widget_set_size_request (G_TYPE_CHECK_INSTANCE_CAST (_tmp14_, gtk_widget_get_type (), GtkWidget), 1024, 768);
#line 100 "BudgieMenu.vala"
	_tmp15_ = win;
#line 100 "BudgieMenu.vala"
	gtk_widget_show_all (G_TYPE_CHECK_INSTANCE_CAST (_tmp15_, gtk_widget_get_type (), GtkWidget));
#line 101 "BudgieMenu.vala"
	gtk_main ();
#line 78 "BudgieMenu.vala"
	_g_object_unref0 (settings);
#line 78 "BudgieMenu.vala"
	_g_object_unref0 (win);
#line 78 "BudgieMenu.vala"
	_g_option_context_free0 (ctx);
#line 543 "BudgieMenu.c"
}


int main (int argc, char ** argv) {
#if !GLIB_CHECK_VERSION (2,35,0)
	g_type_init ();
#endif
#line 78 "BudgieMenu.vala"
	_vala_main (argv, argc);
#line 78 "BudgieMenu.vala"
	return 0;
#line 555 "BudgieMenu.c"
}



